#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

scrappers:
  userbenchmark-cpu:
    enabled: false
    schedule: "0  0 * * *"
    command: ["./userbenchmark_scraper.py", "-t", "CPU", "-o", "data/userbenchmark_cpu.csv"]
  userbenchmark-gpu:
    enabled: false
    schedule: "30 1 * * *"
    command: ["./userbenchmark_scraper.py", "-t", "GPU", "-o", "data/userbenchmark_gpu.csv"]
  userbenchmark-ssd:
    enabled: false
    schedule: "0  3 * * *"
    command: ["./userbenchmark_scraper.py", "-t", "SSD", "-o", "data/userbenchmark_ssd.csv"]
  userbenchmark-hdd:
    enabled: false
    schedule: "30 4 * * *"
    command: ["./userbenchmark_scraper.py", "-t", "HDD", "-o", "data/userbenchmark_hdd.csv"]
  userbenchmark-ram:
    enabled: false
    schedule: "0  6 * * *"
    command: ["./userbenchmark_scraper.py", "-t", "RAM", "-o", "data/userbenchmark_ram.csv"]
  userbenchmark-usb:
    enabled: false
    schedule: "30 7 * * *"
    command: ["./userbenchmark_scraper.py", "-t", "USB", "-o", "data/userbenchmark_usb.csv"]
  passmark-cpu:
    enabled: false
    schedule: "0  0 * * *"
    command: ["./passmark_scraper.py", "-t", "CPU", "-o", "data/passmark_cpu.csv"]
  passmark-gpu:
    enabled: false
    schedule: "30 1 * * *"
    command: ["./passmark_scraper.py", "-t", "GPU", "-o", "data/passmark_gpu.csv"]
  passmark-hdd:
    enabled: false
    schedule: "0  3 * * *"
    command: ["./passmark_scraper.py", "-t", "HDD", "-o", "data/passmark_hdd.csv"]


defaultPodOptions:
  securityContext:
    fsGroup: 65534
    fsGroupChangePolicy: Always


controllers:
  main:
    containers:
      webserver:
        image:
          repository: ghcr.io/juniorjpdj/benchmarks-scraper
          pullPolicy: Always
          tag: latest

        securityContext:
          capabilities:
            drop:
              - ALL

          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534


persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /app/data/
        readOnly: false
    size: 100Mi


service:
  main:
    controller: main
    ports:
      http:
        port: 9999


ingress:
  main:
    enabled: false
    hosts:
      - host: benchmarks.example.local
        paths:
          - path: /
            service:
              name: main
              port: http
