{{/* Preprocess values and prepare config file */}}
{{- define "benchmarks.preprocess" -}}
controllers:
{{- range $k, $v:= .Values.scrappers }}
{{- if $v.enabled }}
  {{ $k }}:
    type: cronjob

    cronjob:
      schedule: {{ quote $v.schedule }}

    containers:
      scrapper:
        command:
          {{- toYaml $v.command | nindent 10 }}
        {{- omit $.Values.controllers.main.containers.webserver "command" | toYaml | nindent 8 }}
{{- end }}
{{- end }}
{{- end -}}
{{- $_ := merge .Values (include "benchmarks.preprocess" . | fromYaml) -}}

{{/* Render the templates */}}
{{- include "bjw-s.common.loader.all" . }}
